### ISSUE TITLE
issue with street names that are also town names

### ISSUE THREAD

**Issue by hornste** [degauss-org/degauss-org.github.io#6]
Hi -- I'm noticing that street names that are also town names are inaccurately identifying the street name as a town. 

For example, here is a list of 2 starbuck's in the town of Dorchester (to avoid PHI):

input file:
001,36 District Ave Dorchester MA 02125
002,45 Morrissey Blvd Dorchester MA 02125

output file:
"36 District Ave Dorchester MA 02125","001","Dorchester Ave","02125","Uphams Corner","MA",42.325528,-71.056844,0.517,"","700","street"
"45 Morrissey Blvd Dorchester MA 02125","002","Dorchester Ave","02125","Uphams Corner","MA",42.325528,-71.056844,0.509,"","701","street"

**Comment by cole-brokamp** [comment]
Hi, we just released version 3.0 of the geocoder with some improvements.  Would you try this new version to see if the same problems arise?

**Comment by hornste** [comment]
I just download version 3.0 and am still getting the same error. 

Here is the output from v3.0

002,45 Morrissey Blvd Dorchester MA 02125,Dorchester Ave,02125,Uphams Corner,MA,42.324828,-71.056844,0.509,street,geoc
oded
001,36 District Ave Dorchester MA 02125,Dorchester Ave,02125,Uphams Corner,MA,42.324828,-71.056844,0.517,street,geocod
ed

**Comment by cole-brokamp** [comment]
The geocoder effectively ignore city and state and only uses zip code to do initial restrictions of its search.  What if you removed the city and state from your addresses?  Would this prevent the problem?

**Comment by hornste** [comment]
Nope, that doesn't seem to work either.

see output:
001,36 District Ave 02125,02125,Uphams Corner,MA,NA,NA,0.502,zip,NA,imprecise_geocode
002,45 Morrissey Blvd 02125,02122,NA,NA,42.293929,-71.047218,0.586,street,Morrissey Blvd,geocoded

**Comment by cole-brokamp** [comment]
The output seems to be working correctly.

First row is saying the geocoder cannot find a street called District Ave in the zipcode 02125 (or its neighboring zipcodes)

In the second row, Morrissey Blvd seems to be in both 02125 and 02122, which is causing the problem.  It looks like the street range files have 45 in 02122 instead of 02125.
